"""Attribution is disabled at the source.

Two independent guards, matching the two ways Claude attribution could reach a
durable repository artifact:

  1. Native Claude Code config in the project ``.claude/settings.json`` blanks
     commit + PR attribution and turns off the session URL.
  2. The repo-controlled PRD commit scripts no longer append a
     ``Co-Authored-By`` trailer, generated-by text, or a Claude session
     identifier / URL.

Both are asserted against the authoritative source file itself (not a proxy),
and each assertion fails loud if the guarantee regresses.
"""

import json
import re
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]

# Tokens that constitute Claude attribution in a commit message or PR body.
# Case-insensitive; each names one of the injection forms the project bans.
_ATTRIBUTION_TOKENS = (
    r"co-authored-by",
    r"claude@anthropic",
    r"generated by claude",
    r"generated with claude",
    r"claude\.ai/code",
    r"claude-session",
    r"session_[0-9a-z]",
)
_ATTRIBUTION_RE = re.compile("|".join(_ATTRIBUTION_TOKENS), re.IGNORECASE)

_PRD_SCRIPTS = ("scripts/prd_open.sh", "scripts/prd_close.sh")


def _settings() -> dict:
    return json.loads((REPO / ".claude" / "settings.json").read_text(encoding="utf-8"))


def test_project_settings_disable_commit_attribution():
    assert _settings().get("attribution", {}).get("commit") == ""


def test_project_settings_disable_pr_attribution():
    assert _settings().get("attribution", {}).get("pr") == ""


def test_project_settings_disable_session_url():
    assert _settings().get("attribution", {}).get("sessionUrl") is False


def test_prd_scripts_emit_no_claude_attribution():
    offenders = []
    for rel in _PRD_SCRIPTS:
        text = (REPO / rel).read_text(encoding="utf-8")
        for n, line in enumerate(text.splitlines(), start=1):
            if _ATTRIBUTION_RE.search(line):
                offenders.append(f"{rel}:{n}: {line.strip()}")
    assert not offenders, "Claude attribution found in PRD scripts:\n" + "\n".join(offenders)
