"""PRD-346: scripts/clean_generated_artifacts.sh restores the seventeen fixed
mutable tracked generated paths and nothing else. Every test drives the helper
in a throwaway git repository under tmp_path; the real repo is never touched."""
from __future__ import annotations

import subprocess
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
SCRIPT = REPO / "scripts" / "clean_generated_artifacts.sh"

GENERATED = [  # the reviewed seventeen (PRD-346); the helper must name exactly these
    "logs/audit.jsonl", "logs/latest_contract.json", "logs/latest_hourly_contract.json",
    "logs/latest_hourly_payload.json", "logs/latest_hourly_run.json", "logs/latest_payload.json",
    "logs/market_map.json", "logs/last_hourly_slot.json", "logs/latest_hourly_market_map.json",
    "logs/latest_run.json", "logs/macro_drivers_snapshot.json", "logs/price_bars_snapshot.json",
    "logs/regime_history.jsonl", "logs/trend_structure_snapshot.json",
    "ui/contract.json", "ui/dashboard.html", "ui/index.html",
]
SOURCE, DURABLE = "cuttingboard/x.py", "data/manual.json"


def _git(cwd: Path, *args: str) -> str:
    return subprocess.run(["git", *args], cwd=cwd, check=True, capture_output=True, text=True).stdout


def _seed(root: Path, paths: list[str]) -> None:
    for rel in paths:
        (root / rel).parent.mkdir(parents=True, exist_ok=True)
        (root / rel).write_text(f"committed {rel}\n")


def _repo(tmp_path: Path, tracked: list[str]) -> Path:
    _git(tmp_path, "init", "-q")
    _git(tmp_path, "config", "user.email", "t@t")
    _git(tmp_path, "config", "user.name", "t")
    _seed(tmp_path, tracked)
    _git(tmp_path, "add", "-A")
    _git(tmp_path, "commit", "-q", "-m", "seed")
    return tmp_path


def _run(cwd: Path) -> subprocess.CompletedProcess:
    return subprocess.run(["bash", str(SCRIPT)], cwd=cwd, capture_output=True, text=True)


def _tree(root: Path) -> dict[str, bytes]:
    return {str(p.relative_to(root)): p.read_bytes() for p in root.rglob("*") if p.is_file() and ".git" not in p.parts}


def test_r1_all_seventeen_generated_paths_restored(tmp_path: Path) -> None:
    repo = _repo(tmp_path, GENERATED)
    for rel in GENERATED:
        (repo / rel).write_text(f"dirty {rel}\n")
    res = _run(repo)
    assert res.returncode == 0, res.stderr
    still_dirty = [ln[3:] for ln in _git(repo, "status", "--short").splitlines()]
    assert still_dirty == [], f"not restored: {still_dirty}"   # M1: a dropped entry is named here


def test_r2_untracked_source_and_durable_sentinels_untouched(tmp_path: Path) -> None:
    untracked_generated = "logs/latest_hourly_market_map.json"   # NAMED in GENERATED, left untracked
    tracked = [p for p in GENERATED if p != untracked_generated] + [SOURCE, DURABLE]
    repo = _repo(tmp_path, tracked)
    (repo / untracked_generated).write_text("untracked generated bytes\n")
    (repo / "notes.txt").write_text("untracked sentinel\n")
    (repo / SOURCE).write_text("modified source\n")
    (repo / DURABLE).write_text("modified durable\n")
    for rel in GENERATED:
        if rel != untracked_generated:
            (repo / rel).write_text(f"dirty {rel}\n")
    before = {rel: (repo / rel).read_bytes() for rel in (untracked_generated, "notes.txt", SOURCE, DURABLE)}
    res = _run(repo)
    assert res.returncode == 0, res.stderr
    for rel, data in before.items():
        assert (repo / rel).exists() and (repo / rel).read_bytes() == data, rel
    assert f"restored: {untracked_generated}" not in res.stdout   # skipped by git ls-files, never deleted


def test_r3_outside_git_work_tree_fails_loud_and_changes_nothing(tmp_path: Path) -> None:
    _seed(tmp_path, GENERATED + [SOURCE])
    before = _tree(tmp_path)
    res = _run(tmp_path)
    assert res.returncode != 0
    assert _tree(tmp_path) == before
